### ISSUE TITLE
Length mismatch: Expected axis has 0 elements, new values have 1 elements

### ISSUE THREAD

**Issue by kab1012** [Ibtastic/Medical-Diagnosis-using-Deep-Learning#1]
I am getting this error after cloning the repo on the 4th code line:

train_data=load_train()
#len(train_data)

**Comment by Ibtastic** [comment]
Did you download the data first? 
If not you can download it from [here](https://www.kaggle.com/paultimothymooney/chest-xray-pneumonia) and unzip the downloaded file in the data directory.
